name: Build and Deploy Angular App

on:
  push:
    branches:
      - master  # Replace with your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust the Node version based on your Angular setup

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Copiar os arquivos do repositorio instalado para o servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.PROD_HOST }}
          username: ${{ vars.PROD_HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/BiniCash/"
          target: /var/www/BiniCash-Frontend
          strip_components: 2

      - name: Reiniciar o lighttpd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PROD_HOST }}
          username: ${{ vars.PROD_HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart lighttpd